---
lang: pt-BR
title: "Cronograma"
---

Nesta página, você encontrará o cronograma completo da disciplina, com
links para os materiais de cada aula, incluindo slides, links para 
tutoriais criados para a disciplina, arquivos quarto (.qmd), 
artigos, e outros recursos que poderão ser disponibilizados.


# Semana 1

## Aula 1 (19/08/2025) 

- **Tópicos:**
  
  - Apresentações
  - Apresentação da Disciplina
  - Ambiente Computacional - instalação e Configuração


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides_aula01.html" width="100%" height="450px"></iframe>
  

- **Arquivo quarto**

  - [01-relatorio (.zip)](arquivos/01-relatorio.zip)


- **Arquivo de dados**

  - [dados (.zip)](arquivos/dados.zip)




# Semana 2

## Aula 2 (26/08/2025) 

- **Tópicos:**
  
  - Curso Intensivo sobre as Ferramentas:
    - Git e GitHub
    - Introdução ao Sistema 
    - Linguagem R
  - Sessão Prática


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides_aula02.html" width="100%" height="450px"></iframe>
  

- **Arquivo quarto: Relatório**

  - [02-relatorio (.zip)](arquivos/02-relatorio.zip)


- **Arquivo quarto: Atividade 1**

  - [01-atividade (.zip)](arquivos/01-atividade.zip)





# Semana 3

## Aula 3 (02/09/2025) 

- **Tópicos:**
  
  - Minicurso Intensivo: Teoria da Probabilidade - Parte 1


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula03.html" width="100%" height="450px"></iframe>
  

- **Atividade 2**

  - [02-atividade.pdf](arquivos/02-atividade.pdf)
  - **Data Limite** para envio pelo Google Sala de Aula: 12/09/2025


- **Template de arquivo quarto (.qmd) para a Atividade 2**

  - [02-atividade-template.zip](arquivos/02-atividade-template.zip)

::: {.callout-tip}
## Atividade 2: Instruções para Resolução e Envio

Vocês tem duas opções para enviar a resolução Atividade 2:

1. Fazer em papel, fotografar, digitalizar e enviar um único arquivo 
pdf contendo a resolução dos exercícios. Nesse caso, é importante 
que os exercícios e sua resolução estejam organizados e legíveis. 

2. Utilizar o template de arquivo quarto (que produz um arquivo html após ser 
renderizado) que preparei para os que desejarem fazer a atividade usando 
o sistema quarto. Entretanto, para utilizar o template, será necessário 
escrever as fórmulas usadas no cálculo das probabilides usando LaTeX. 
Assim, para ajudar os que desejarem usar esta estratégia, elaborei as 
dicas exibidas no quadro abaix. Caso opte por usar o template, lembre-se de 
abrir seu projeto RStudio da disciplina, criar a subpasta **02-atividade** 
dentro da pasta **atividades**, baixar, descompactar e mover o arquivo 
`02-atividade-template.qmd` dentro da subpasta 02-atividade, 
preferencialmente usando o terminal Git Bash do RStudio e a 
cadeia de comandos: 


#### Dicas para escrever equações com Latex nos sistema Quarto

Ao responder as questões, será necessário escrever **fórmulas matemáticas** 
para o cálculo das probabilides. E, como sabemos, é possível escrever 
matemática em arquivos quarto usando LaTeX.

Existem duas formas principais de escrever equações:

#### Equações em linha

Use **um `$` no início e um `$` no fim** da equação.  

Exemplo:

``` markdown
A probabilidade condicional é dada por $P(A|B) = \frac{P(A \cap B)}{P(B)}$.
```

Após renderizar o arquivo você terá: 

A probabilidade condicional é dada por $P(A|B) = \frac{P(A \cap B)}{P(B)}$.


#### Equações destacadas (em bloco)

Use **`$$` antes e depois** do bloco de fórmulas

Exemplo:

``` markdown
$$
P(A \cup B) = P(A) + P(B) - P(A \cap B) = 0.4 + 0.3 - 0.2 = 0.5
$$
```

E, após renderizar o arquivo, você terá: 

$$
P(A \cup B) = P(A) + P(B) - P(A \cap B) = 0.4 + 0.3 - 0.2 = 0.5
$$


#### Várias linhas de cálculo

Dentro de um mesmo bloco  use `$$...$$` e `\begin{aling*}` e `\begin{aling*}`, 
e use `\\` para quebrar linhas.

Exemplo:

```markdown
$$
\begin{align*}
P(A|B) = \frac{P(A \cap B)}{P(B)} \\
= \frac{0.12}{0.30} \\
= 0.40
\begin{align*}
$$
```

E, após renderizar o arquivo, você terá: 

$$
\begin{align*}
P(A|B) &= \frac{P(A \cap B)}{P(B)} \\
       &= \frac{0.12}{0.30} \\
       &= 0.40
\end{align*}
$$



#### Funções LaTeX úteis para probabilidade básica

- `\cup` → produz $\cup$ = união  

- `\cap` → produz $\cap$  = interseção  

- `\bar{A}` → produz $\bar{A}$ = complemento de $A$ (Obs: para obter o complemento de 
uma operação envolvendo mais de um evento, é preferível usar a função `\overline{}`),
por exemplo `P(\overline{A \cap B})` produz $P(\overline{A \cap B}))$  

- `\frac{a}{b}` → produz $\frac{a}{b}$ = fração  

- `$x^2$` → produz $x^2$ = expoente 

- `X_1` → produz $X_1$ = variável com subscrito  

- `f_{X_1}(x_1)` → produz $f_{X_1}(x_1)$ = densidade da distribuicão marginal de $X_1$  

- `f_{X_1,X_2}(x_1,x_2)` → produz $f_{X_1,X_2}(x_1,x_2)$ = densidade da distribuição conjunta de $X_1$ e $X_2$  

- `f_{X_1|X_2}(X_1|X_2 = x_2)` → produz $f_{X_1|X_2}(X_1|X_2 = x_2)$ = densidade da distribuição condicional de $X_1$ dado $X_2 = x_2$  


**Sugestão:**  

Use **equações em linha** (`$...$`) para respostas curtas e simples, e a 
a maioria dos exercícios envolve cálculos simples.

e **blocos de equação** (`$$...$$`) quando precisar mostrar cálculos 
mais longos.
:::





# Semana 4

## Aula 4 (09/09/2025) 

- **Tópicos:**
  
  - Minicurso Intensivo: Teoria da Probabilidade - Parte 2


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula04.html" width="100%" height="450px"></iframe>
  

- **Arquivo quarto: Relatório**

  - [03-relatorio (.zip)](arquivos/03-relatorio.zip)
 



# Semana 5

## Aula 5 (16/09/2025) 

- **Tópicos:**
  
  - Minicurso Intensivo: Teoria da Probabilidade - Parte 3


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula05.html" width="100%" height="450px"></iframe>





# Semana 6

## Aula 6 (23/09/2025) 

- **Tópicos:**
  
  - Minicurso Intensivo: Métodos de Inferência Estatística I


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides_aula06.html" width="100%" height="450px"></iframe>





# Semana 7

## Aula 7 (30/09/2025) 

- **Tópicos:**
  
  - Minicurso Intensivo: Métodos de Inferência Estatística II
  - Fim do minicurso

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula07.html" width="100%" height="450px"></iframe>




# Semana 8

## Aula 8 (07/10/2025) 

- **Tópicos:**
  
  - Modelo de Regressão Linear Simples
  - Avaliação 1

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula08.html" width="100%" height="450px"></iframe>


- **Arquivo quarto para a aula**

  - [04-relatorio.zip](arquivos/04-relatorio.zip)
  - Baixe o arquivo, descompacte e coloque todos os arquivos dentro da subpasta `04-relatorio`


- **Arquivo de dados (.rda)**

  - [dados-hedge-clean.zip](arquivos/dados-hedge-clean.zip)
  - [dados-capm-clean.zip](arquivos/dados-capm-clean.zip)
  - Baixe os dois arquivos, descompacte e coloque ambos na pasta `dados/processados` do seu projeto


- **Avaliação 1**

  ::: {.callout-tip}
  ## Avaliação 1 

  [**Clique aqui para acessar a Avaliação 1**](/arquivos/01-avaliacao.html){target="_blank"}
  
  [O1-avaliacao-template.zip](arquivos/01-avaliacao-template.zip)
  :::


  ::: {.callout-tip}
  ## Estruturando seu Projeto RStudio para a Avaliação 1

  1. Abra o RStudio e o seu Projeto RStudio da disciplina.

  2. Crie uma pasta chamada **avaliacoes** na raiz do seu Projeto RStudio

  3. Dentro da pasta **avaliacoes** , crie uma subpasta chamada **01-avaliacao**

  4. Baixe o arquivo **01-avaliacao-template.zip**, descompacte esse arquivo, 
  copie/recorte o arquivo `01-avaliacao-template.qmd` e salve-o na 
  subpasta **01-avaliacao** que você acabou de criar

  5. Renomeie o arquivo `01-avaliacao-template.qmd` para 
  `01-avaliacao-seunome.qmd`

  8. Escreva seu nome na chave `author: "SEU NOME AQUI"` do cabeçalho yaml 
  e resolva as questões.
  :::





# Semana 9

## Aula 9 (14/10/2025) 

- **Tópicos:**
  
  - Modelo de Regressão Linear Múltipla I

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula09.html" width="100%" height="450px"></iframe>



- **Arquivo quarto para a aula**

  - [05-relatorio.zip](arquivos/05-relatorio.zip)
  - Baixe o arquivo, descompacte e coloque **todos** os arquivos dentro da subpasta `relatorios/05-relatorio/`





# Semana 10

## Aula 10 (21/10/2025) 

- **Tópicos:**
  
  - Modelo de Regressão Linear Múltipla II

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula10.html" width="100%" height="450px"></iframe>



- **Arquivo quarto para a aula**

  - [06-relatorio.zip](arquivos/06-relatorio.zip)
  - Baixe o arquivo, descompacte e coloque **todos** os arquivos dentro da subpasta `relatorios/06-relatorio/`


- **Arquivo de dados (.xls)**

  - [macro.zip](arquivos/macro.zip)
  - Baixe o arquivo, descompacte e coloque o arquivo `macro.xls` dentro da subpasta `dados/brutos/`





# Semana 11

## Aula 11 (28/10/2025) 

- **Tópicos:**
  
  - Testes de Estabilidade de Parâmetros
  - Diagnóstico e Teste de Normalidade dos Resíduos
  - Diagnóstico de Observações Influentes
  - Regressão Robusta (ou Resistente)

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula11.html" width="100%" height="450px"></iframe>



- **Arquivo quarto para a aula**

  - [07-relatorio.zip](arquivos/07-relatorio.zip)
  - Baixe o arquivo, descompacte e coloque **todos** os arquivos dentro da subpasta `relatorios/07-relatorio/`




# Semana 12

## Aula 12 (04/11/2025) 

- **Tópicos:**
  
  - Modelos para Variáveis Dependentes Limitadas

    - Motivação
    - Modelos de Escolha Discreta
    - Modelo Linear de Probabilidade
    - Modelos Probit e Logit
    - Modelos Lineares Generalizados
    - Estimação por Máxima Verossimilhança
    - Procedimentos de Inferência 
    - Interpretação das Estimativas
    - Medidas da Qualidade do Ajuste
    - Modelos Multinomiais

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula12.html" width="100%" height="450px"></iframe>



- **Arquivo quarto para a aula**

  - [08-relatorio.zip](arquivos/08-relatorio.zip)
  - Baixe o arquivo, descompacte e coloque o arquivo .qmd dentro da subpasta `relatorios/08-relatorio/`




# Semana 13

## Aula 13 (11/11/2025) 

- **Tópicos:**
  
    - Exogeneidade: Revisão
    - Consistência de Estimadores
    - Viés de Variável Omitida
    - Erro de Mensuração
    - Causalidade
    - Regressão com Variáveis Instrumentais


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  ::: 

  <iframe src="/slides/slides-aula13.html" width="100%" height="450px"></iframe>


- **Arquivo quarto para a aula**

  - [09-relatorio.zip](arquivos/09-relatorio.zip)
  - Baixe o arquivo, descompacte e coloque o arquivo .qmd dentro da subpasta `relatorios/09-relatorio/`





# Semana 14

## Aula 14 (11/11/2025) 


- **Atividade 3**

- Arquivos necessários para a atividade

  - [03-atividade](arquivos/03-atividade.html){target="_blank"} - Clique para acessar a atividade
  - [03-template-atividade.zip](arquivos/03-template-atividade.zip) - Template de arquivo quarto,
  que produz um arquivo html após ser renderizado, para resolver e enviar a atividade.


  - **Data Limite** para envio do arquivo html compactado (.zip) pelo Google Sala de Aula: 17 horas de 18/11/2025 